INFO:     Will watch for changes in these directories: ['/root/python_projects/flight_deals_alert']
INFO:     Uvicorn running on http://116.202.210.102:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [156401] using StatReload
INFO:     Started server process [156404]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     119.82.82.27:57008 - "OPTIONS /v1/register HTTP/1.1" 200 OK
INFO:     119.82.82.27:57009 - "POST /v1/register HTTP/1.1" 307 Temporary Redirect
INFO:     119.82.82.27:57008 - "OPTIONS /v1/register/ HTTP/1.1" 200 OK
INFO:     119.82.82.27:57009 - "POST /v1/register/ HTTP/1.1" 201 Created
INFO:     119.82.82.27:57050 - "OPTIONS /v1/login/ HTTP/1.1" 200 OK
INFO:     119.82.82.27:57052 - "POST /v1/login/ HTTP/1.1" 400 Bad Request
INFO:     93.11.197.240:54527 - "GET / HTTP/1.0" 404 Not Found
INFO:     198.235.24.199:59274 - "GET / HTTP/1.1" 404 Not Found
INFO:     119.82.82.27:57360 - "POST /v1/logout/8 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "/root/python_projects/flight_deals_alert/app/routes.py", line 280, in logout
    return JSONResponse(status=200, content={"mesage": "You have been logged out"})
TypeError: JSONResponse.__init__() got an unexpected keyword argument 'status'
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [156404]
INFO:     Started server process [158481]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     119.82.82.27:57413 - "POST /v1/logout/8 HTTP/1.1" 200 OK
INFO:     119.82.82.27:57419 - "OPTIONS /v1/login/ HTTP/1.1" 200 OK
INFO:     119.82.82.27:57421 - "POST /v1/login/ HTTP/1.1" 400 Bad Request
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [158481]
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Started server process [159201]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [159213]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     119.82.82.27:57550 - "POST /v1/logout/8 HTTP/1.1" 200 OK
INFO:     119.82.82.27:57551 - "POST /v1/login/ HTTP/1.1" 201 Created
INFO:     119.82.82.27:57551 - "GET /v1/get-profile/8 HTTP/1.1" 200 OK
WARNING:  StatReload detected changes in 'app/models.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [159213]
INFO:     Started server process [159833]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [159833]
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Started server process [160546]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Started server process [160547]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Started server process [160551]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [160554]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [160554]
Process SpawnProcess-10:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/python_projects/flight_deals_alert/app/routes.py", line 265
    "created_at": str(existing_user.created_at)
                  ^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
Process SpawnProcess-11:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/python_projects/flight_deals_alert/app/routes.py", line 265
    "created_at": str(existing_user.created_at)
                  ^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
Process SpawnProcess-12:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/python_projects/flight_deals_alert/env/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/python_projects/flight_deals_alert/app/routes.py", line 265
    "created_at": str(existing_user.created_at)
                  ^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Started server process [160628]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [160628]
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Started server process [160709]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [160710]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [160710]
INFO:     Started server process [160779]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     119.82.82.27:58018 - "OPTIONS /v1/register HTTP/1.1" 200 OK
INFO:     119.82.82.27:58019 - "POST /v1/register HTTP/1.1" 307 Temporary Redirect
INFO:     119.82.82.27:58018 - "OPTIONS /v1/register/ HTTP/1.1" 200 OK
INFO:     119.82.82.27:58019 - "POST /v1/register/ HTTP/1.1" 201 Created
INFO:     119.82.82.27:58040 - "POST /v1/logout/9 HTTP/1.1" 200 OK
INFO:     119.82.82.27:58053 - "OPTIONS /v1/login/ HTTP/1.1" 200 OK
INFO:     119.82.82.27:58053 - "POST /v1/login/ HTTP/1.1" 201 Created
INFO:     119.82.82.27:58053 - "GET /v1/get-profile/9 HTTP/1.1" 400 Bad Request
INFO:     119.82.82.27:58169 - "POST /v1/register HTTP/1.1" 307 Temporary Redirect
INFO:     119.82.82.27:58170 - "POST /v1/register/ HTTP/1.1" 201 Created
INFO:     119.82.82.27:58178 - "POST /v1/logout/10 HTTP/1.1" 200 OK
INFO:     119.82.82.27:58179 - "POST /v1/login/ HTTP/1.1" 201 Created
INFO:     119.82.82.27:58179 - "GET /v1/get-profile/10 HTTP/1.1" 400 Bad Request
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [160779]
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Started server process [162026]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [162029]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [162029]
INFO:     Started server process [162075]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'app/routes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [162075]
INFO:     Started server process [162104]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     119.82.82.27:58309 - "POST /v1/logout/10 HTTP/1.1" 200 OK
INFO:     119.82.82.27:58310 - "POST /v1/login/ HTTP/1.1" 201 Created
INFO:     119.82.82.27:58310 - "GET /v1/get-profile/10 HTTP/1.1" 400 Bad Request
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
INFO:     119.82.82.27:58383 - "GET /verify/50d36d3e-e256-4642-a72e-59a900a92c0f HTTP/1.1" 200 OK
INFO:     119.82.82.27:58383 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     49.44.84.101:40912 - "GET /verify/50d36d3e-e256-4642-a72e-59a900a92c0f HTTP/1.1" 400 Bad Request
INFO:     49.44.78.135:40010 - "GET /verify/50d36d3e-e256-4642-a72e-59a900a92c0f HTTP/1.1" 400 Bad Request
INFO:     119.82.82.27:58751 - "OPTIONS /v1/register HTTP/1.1" 200 OK
INFO:     119.82.82.27:58752 - "POST /v1/register HTTP/1.1" 307 Temporary Redirect
INFO:     119.82.82.27:58751 - "OPTIONS /v1/register/ HTTP/1.1" 200 OK
INFO:     119.82.82.27:58752 - "POST /v1/register/ HTTP/1.1" 201 Created
INFO:     119.82.82.27:58765 - "POST /v1/logout/11 HTTP/1.1" 200 OK
INFO:     119.82.82.27:58772 - "POST /v1/logout/11 HTTP/1.1" 200 OK
INFO:     119.82.82.27:58786 - "OPTIONS /v1/login/ HTTP/1.1" 200 OK
INFO:     119.82.82.27:58786 - "POST /v1/login/ HTTP/1.1" 201 Created
INFO:     119.82.82.27:58786 - "GET /v1/get-profile/11 HTTP/1.1" 400 Bad Request
INFO:     119.82.82.27:58795 - "GET /v1/get-profile/11 HTTP/1.1" 400 Bad Request
WARNING:  Invalid HTTP request received.
INFO:     119.82.82.27:58816 - "GET /verify/8a6279e1-7e49-4469-9a39-d946855cc77d HTTP/1.1" 200 OK
WARNING:  Invalid HTTP request received.
